modelname:  debug

# Data:
input_data_src: data/WMT14/en_src
input_data_trg: data/WMT14/fr_trg
restart : 1
batch_size : 3
valid_batch_size : 2

# Logging:
save_checkpoint_every: 5000
losses_log_every : 100

optim : adam
rnn_size_src : 20
rnn_size_trg : 20
dim_word_src : 12
dim_word_trg : 12
num_layers_src : 1
num_layers_trg : 1
bidirectional : 1
decode: greedy 
model: attention

# Loss
loss_version : ml
