modelname : strat_rhamming_pool2_tsent04_a03
model: attention

# Data:
input_data_src: data/WMT14/en_src
input_data_trg: data/WMT14/fr_trg

# batch_size: 10
# valid_batch_size: 25

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub  : 2
stratify_reward  : 1
tau_sent : .4
alpha_sent : 0.3
